// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheDoxaFlameAPIApp.Models;

public partial class AdminDashboardSetting
{
    public int SettingsId { get; set; }

    public int ChurchId { get; set; }

    public string Theme { get; set; }

    public bool? NotificationsEnabled { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Church Church { get; set; }
}