// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheDoxaFlameAPIApp.Models;

public partial class CongregationPreference
{
    public int PreferenceId { get; set; }

    public int UserId { get; set; }

    public int ChurchId { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Church Church { get; set; }

    public virtual User User { get; set; }
}