// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheDoxaFlameAPIApp.Models;

public partial class FeedbackSupportTicket
{
    public int TicketId { get; set; }

    public int UserId { get; set; }

    public string Message { get; set; }

    public string Status { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ResolvedDate { get; set; }

    public virtual User User { get; set; }
}