// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheDoxaFlameAPIApp.Models;

public partial class Pastor
{
    public int PastorId { get; set; }

    public int ChurchId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Church Church { get; set; }

    public virtual ICollection<Speaker> Speakers { get; set; } = new List<Speaker>();
}