// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheDoxaFlameAPIApp.Models;

public partial class Playlist
{
    public int PlaylistId { get; set; }

    public int ServiceId { get; set; }

    public int SongId { get; set; }

    public int Order { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Service Service { get; set; }

    public virtual Song Song { get; set; }
}