// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheDoxaFlameAPIApp.Models;

public partial class Song
{
    public int SongId { get; set; }

    public string Title { get; set; }

    public string Artist { get; set; }

    public string Url { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<Playlist> Playlists { get; set; } = new List<Playlist>();
}